name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Anutri03 # ← Must match your GitHub username
          svg_output_path: assets/github-contribution-grid-snake.svg
          color1: 'ff0000'  # Red 
          color2: '00ff00'  # Green 
          color3: '0000ff'  # Blue 
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'docs: Update snake'
          add: 'assets/github-contribution-grid-snake.svg'
